version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "narayanaitrecruiter"
github_repo = "kjell"
deployment_branch = "master"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::661425616205:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-vTGBxFCkqhyj"
cloudformation_execution_role = "arn:aws:iam::661425616205:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-1iDuTOkojBBh"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-rlvfapr0ebg4"
image_repository = ""
region = "us-west-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::661425616205:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-EI6xShw5vyWe"
cloudformation_execution_role = "arn:aws:iam::661425616205:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-qIp9XllcExsQ"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-sm7smu42rqou"
image_repository = ""
region = "us-west-1"
